### ISSUE TITLE
Perfect square

### ISSUE THREAD

**Issue by tiepvupsu** [tiepvupsu/coding_exercise#1]
https://leetcode.com/problems/perfect-squares/description/

Given a positive integer n, find the least number of perfect square numbers (for example, 1, 4, 9, 16, ...) which sum to n.

For example, given n = 12, return 3 because 12 = 4 + 4 + 4; given n = 13, return 2 because 13 = 4 + 9.

**Comment by thainv0212** [comment]
I think ```Backtracking``` and ```Branch and Bound``` should be appropriate.

**Comment by thainv0212** [comment]
I think```Greedy``` algorithm should be ok :D

**Comment by thainv0212** [comment]
I thought ```Greedy``` would be OK, but it found the first solution and not the best.So I tried ```Branch and Bound``` and it worked :D

**Comment by tiepvupsu** [comment]
`class Solution(object):
    # DP solution
    _dp = [0]
    def numSquares(self, n):
        dp = self._dp 
        while len(dp) <= n:
            dp += [min(dp[-i*i] for i in range(1, int(len(dp)**0.5)+1)) + 1]
        return dp[n]
    
    # BFS solution 
    # def numSquares(self, n):
    #     if n < 2: return n 
    #     sqs = [i*i for i in range(1, int(n**.5)+1)]
    #     if sqs[-1] == n: return 1 
    #     # remain = set([n])
    #     remain = {n}
    #     cnt = 0 
    #     while remain: 
    #         cnt += 1
    #         tmp = set()
    #         for m in remain:
    #             for s in sqs:
    #                 if s > m: break 
    #                 if s == m: return cnt 
    #                 tmp.add(m-s)
    #         remain = tmp 

    # def numSquares(self,n):
    #     dp = [0]*(n+1)
    #     for i in range(1, n+1):
    #         dp[i] = min([dp[i-j*j] for j in range(1, int(i**.5)+1)]) + 1
    #     return dp[-1]`
